### ISSUE TITLE
No matching distribution found for wheel==0.30

### ISSUE THREAD

**Issue by aik7** [5G-Framework/volttron-docker#1]
```
$ docker-compose up
...
volttron1    | No matching distribution found for wheel==0.30
volttron1    | Platform instance name set to: volttron1
volttron1    | Traceback (most recent call last):
volttron1    |   File "/startup/setup-platform.py", line 371, in <module>
volttron1    |     configure_platform(platform_cfg_tmp, config_tmp)
volttron1    |   File "/startup/setup-platform.py", line 198, in configure_platform
volttron1    |     _install_required_deps()
volttron1    |   File "/startup/setup-platform.py", line 71, in _install_required_deps
volttron1    |     subprocess.check_call(install_cmd)
volttron1    |   File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
volttron1    |     raise CalledProcessError(retcode, cmd)
volttron1    | subprocess.CalledProcessError: Command '['pip3', 'install', '--no-deps', 'wheel==0.30']' returned non-zero exit status 1.
volttron1    | error running setup-platform.py
```

```
$ pip3 install --no-deps wheel==0.30
Requirement already satisfied: wheel==0.30 in ...
```

**Comment by aik7** [comment]
The README specified the following requirements:
```
Docker ^20.10.8
Docker-compose ^3.4
```
Using my machine,
```
sudo docker -v
Docker version 20.10.12
$ sudo docker-compose -v
docker-compose version 1.18.0
```

In `docker_install_ubuntu.sh`, `DOCKER_COMPOSE_VERSION=1.18.0`.

**Comment by aik7** [comment]
Restated my terminal, and fixed this issue.
